In [27]:
import numpy as np

In [6]:
# 可以用array()函數來執行一維陣列(串列(list)或元組(tuple))
list1 = [1,2,3,4]
list2 = [5,6,7,8]
np1 = np.array(list1)
np2 = np.array(list2)
print(np1,np2,end='\n')
print(type(list1),type(list2))


[1 2 3 4] [5 6 7 8]
<class 'list'> <class 'list'>


### 設定陣列資料格式:dtype

In [3]:
np3 = np.array([1,2,3,4,5],dtype=float)
print(np3)
np4 = np.array([1,2,3,4,5],dtype=int)
print(np4)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


### 建立有序整數陣列:arange()

In [10]:
nplist=np.arange(1,10)#跟range相似
print(nplist)

[1 2 3 4 5 6 7 8 9]


### 建立等距陣列:linspace()

In [20]:
linspace = np.linspace(1,20,2)
print(linspace)# 意思是1~20之間等距的取得2個元素。

[ 1. 20.]


### 建立同值陣列:zeros()或ones()

In [24]:
zeros = np.zeros(10,)
print(zeros)# 建立全部零的陣列
ones = np.ones(10,)
print(ones)# 建立全部一的陣列


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 建立多維陣列
* ndim屬性:顯示陣列的維度。
* shape屬性:顯示陣列的維度形狀。
* size屬性:顯示陣列內所有的元素數量。

In [26]:
listdata = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
numpy1 = np.array(listdata)
print(numpy1)
print("維度:",numpy1.ndim)
print("形狀:",numpy1.shape)
print("數量:",numpy1.size)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
維度: 2
形狀: (3, 5)
數量: 15


### 改變陣列形狀:reshape()


In [56]:
adata = np.arange(1,20+1)
print(adata)
rdata = adata.reshape((4,5))
print(rdata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [65]:
listdata = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
list1 = np.array(listdata)
rdata = list1.reshape((3,5))
print(rdata)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### numpy陣列取值

In [96]:
na = np.arange(1,6)
print(na)
print(na[0])#取得是1
print(na[1:5])#取得是[2 3 4 5]
print(na[:])#f取得是全部
print(na[1:5:1])# [2 3 4 5]
print(na[5:1:-1])# [5 4 3]


[1 2 3 4 5]
1
[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5]
[5 4 3]
