In [2]:
import numpy as np

In [6]:
# 可以用array()函數來執行一維陣列(串列(list)或元組(tuple))
list1 = [1,2,3,4]
list2 = [5,6,7,8]
np1 = np.array(list1)
np2 = np.array(list2)
print(np1,np2,end='\n')
print(type(list1),type(list2))


[1 2 3 4] [5 6 7 8]
<class 'list'> <class 'list'>


### 設定陣列資料格式:dtype

In [3]:
np3 = np.array([1,2,3,4,5],dtype=float)
print(np3)
np4 = np.array([1,2,3,4,5],dtype=int)
print(np4)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


### 建立有序整數陣列:arange()

In [10]:
nplist=np.arange(1,10)#跟range相似
print(nplist)

[1 2 3 4 5 6 7 8 9]


### 建立等距陣列:linspace()

In [20]:
linspace = np.linspace(1,20,2)
print(linspace)# 意思是1~20之間等距的取得2個元素。

[ 1. 20.]


### 建立同值陣列:zeros()或ones()

In [24]:
zeros = np.zeros(10,)
print(zeros)# 建立全部零的陣列
ones = np.ones(10,)
print(ones)# 建立全部一的陣列


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 建立多維陣列
* ndim屬性:顯示陣列的維度。
* shape屬性:顯示陣列的維度形狀。
* size屬性:顯示陣列內所有的元素數量。

In [26]:
listdata = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
numpy1 = np.array(listdata)
print(numpy1)
print("維度:",numpy1.ndim)
print("形狀:",numpy1.shape)
print("數量:",numpy1.size)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
維度: 2
形狀: (3, 5)
數量: 15


### 改變陣列形狀:reshape()


In [56]:
adata = np.arange(1,20+1)
print(adata)
rdata = adata.reshape((4,5))
print(rdata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [65]:
listdata = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
list1 = np.array(listdata)
rdata = list1.reshape((3,5))
print(rdata)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### numpy陣列取值

In [96]:
# 一維陣列取值
na = np.arange(1,6)
print(na)
print(na[0])#取得是1
print(na[1:5])#取得是[2 3 4 5]
print(na[:])#f取得是全部
print(na[1:5:1])# [2 3 4 5]
print(na[5:1:-1])# [5 4 3]


[1 2 3 4 5]
1
[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5]
[5 4 3]


In [16]:
# 多維陣列取值
listna = np.arange(1,20+1).reshape(4,5)
print(listna)# 全部的串列資料
print(listna[0][1:2])# [2]
print(listna[3][3:1:-1])# [19 18]
print(listna[1,1:3])# [7 8]
print(listna[:,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[2]
[19 18]
[7 8]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


# 產生隨機資料(Numpy.random mouble)
* rand(d0,d1,.....dn):依設定維度形狀，返回0~1之間的隨機浮點數資料。
* randn(d0,d1,.....dn):依設定維度形狀，返回常態分佈的隨機浮點數資料。
* randint(最低，[最高,size]):依設定值範圍(包含最低，不含最高)返回隨機浮點數資料，size可設定返回資料的維度形狀。
* random(size)、random_sample(size)、sample(size):依設定的維度形狀size返回隨機資料，返回0~1之間的隨機浮點數資料。
* choice(陣列(array),size[,replace]):在指定的陣列中取值，依設定的維度形狀size返回隨機資料;若隨機資料是整數時，結果為
arange(整數)設定陣列；replace=Flase會返回不重複的資料。

In [8]:
print("1.產生2x3 0~1之間的隨機浮點數\n",np.random.rand(2,3))
print("2.產生2x3常態分佈的隨機浮點數\n",np.random.randn(2,3))
print("3.產生2~10(不含10)隨機整數\n",np.random.randint(2,10))
print("4.產生2~4(不含5)5個的隨機整數\n",np.random.randint(2,4,[5]))
print("5.產生3個0~1之間的隨機浮點數\n",np.random.random(3),np.random.random_sample(3),np.random.sample(3))
print("6.產生0~4(不含五)2x3的隨機整數\n",np.random.choice(5,[2,3]))
print("7.產生0~42(不含五)6個的隨機整數\n",np.random.choice(43,6,replace=False))


1.產生2x3 0~1之間的隨機浮點數
 [[0.23752959 0.7668777  0.07187311]
 [0.55585675 0.85050238 0.03279257]]
2.產生2x3常態分佈的隨機浮點數
 [[ 2.16751007 -1.69163173  0.84550018]
 [ 0.85307576 -1.06396269 -0.39405836]]
3.產生2~10(不含10)隨機整數
 8
4.產生2~4(不含5)5個的隨機整數
 [2 2 2 3 2]
5.產生3個0~1之間的隨機浮點數
 [0.28659794 0.85161654 0.40928343] [0.66973767 0.73390136 0.00117289] [0.14318969 0.06587248 0.27578386]
6.產生0~4(不含五)2x3的隨機整數
 [[2 3 2]
 [4 1 2]]
7.產生0~42(不含五)6個的隨機整數
 [10 23 20  7 39 12]


In [31]:
# 讀取檔案取值:genfromtext()
# with open("test6.csv","r",encoding="utf-8") as f:
#     print(f.read())
a = np.genfromtxt('test6.csv',delimiter=",",skip_header=1)
print(a.shape)


(4, 2)
